public void modcaucusclick(GButton source, GEvent event) { //_CODE_:modcaucus:743149:
  background(backgroundcolour);
  clearscreen();
  modetype = "modcaucus";
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
      mode = new GLabel(this, width / 2, 50, 500, 200);
      mode.setFont(new Font("Arial", Font.PLAIN, 40));
      mode.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
      mode.setText("");
      mode.setText("Moderated Caucus");
  positionspeakingimage = loadImage("images/" + positionarray.get(numspeak).getImageurl());
  image(positionspeakingimage, (width / 2 - positionspeakingimage.width / 2/10) - width/6, ((height / 2) - positionspeakingimage.height/2/10) - height/5, positionspeakingimage.width/8, positionspeakingimage.height/8);
  positionspeaking.setTextAlign(GAlign.CENTER, GAlign.TOP);
  positionspeaking.setText(this.positionarray.get(numspeak).getPosition());
  positionspeaking.setOpaque(false);
  positionspeaking.setVisible(true);
  setmaxspeak = new GTextField(this, 2 * width /3, height / 4, 80, 30);
  setmaxspeak.setOpaque(true);
  setmaxspeak.addEventHandler(this, "setmaxspeakchange");
  setmaxcaucus = new GTextField(this, 2 * width /3, height / 4 + setmaxspeak.getHeight(), 80, 30);
  setmaxcaucus.setOpaque(true);
  setmaxcaucus.addEventHandler(this, "setmaxcaucuschange");
  loadingbar = loadImage("images/loadingbar.png");
  image(loadingbar, width / 4, 2 * height / 3, width / 2, loadingbar.height);
  loadingbar2 = loadImage("images/loadingbar.png");
  image(loadingbar2, width / 4, 2 * height / 3 + loadingbar.height, width / 2, loadingbar.height);
  loadingbarinside = loadImage("images/loadingbarinside.png");
  loadingbarcaucus = loadImage("images/loadingbarinside.png");
  start = new GButton(this, width / 2 - 2 * width / 7, 6 * height / 7, width / 7, 40);
  start.setText("Start");
  start.addEventHandler(this, "startclick");
  next = new GButton(this, width / 2 - width / 7, 6 * height / 7, width / 7, 40);
  next.setText("Next");
  next.addEventHandler(this, "nextclick");
  reset = new GButton(this, width / 2, 6 * height / 7, width / 7, 40);
  reset.setText("Reset");
  reset.addEventHandler(this, "resetclick");
  pause = new GButton(this, width / 2 +  width/7, 6 * height / 7, width / 7, 40);
  pause.setText("Pause");
  pause.addEventHandler(this, "pauseclick");
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  speakerdrop = new GDropList(this, width - width / 3, height / 3, 250, 300, 10, 12);
  speakerdrop.setItems(positionnames, 0);
  speakerdrop.addEventHandler(this, "speakerdrop");
  perpetual = new GCheckbox(this, width - width / 3, height / 4 - setmaxspeak.getHeight(), 250, 30, "Perpetual? (Crisis)");
  perpetual.setOpaque(false);
  perpetual.addEventHandler(this, "perpetualclicked");
} //_CODE_:modcaucus:743149:
